### ISSUE TITLE
Use ig/resume-key to avoid disconnecting and reconnecting

### ISSUE THREAD

**Issue by dhryniewicz** [magnetcoop/pubsub#4]
I might be wrong but I think that if you define `ig/resume-key` then you control whether you want to halt+init the key or not.

Example:
https://github.com/duct-framework/server.figwheel/blob/master/src/duct/server/figwheel.clj#L116-L122
```clojure
(defmethod ig/resume-key :duct.server/figwheel [key opts old-opts old-impl]
  (if (and (:server old-impl) (= (:builds opts) (:builds old-opts)))
    (doto old-impl
      (build-cljs)
      (refresh-css))
    (do (ig/halt-key! key old-impl)
        (ig/init-key  key opts))))
```

**Comment by iarenaza** [comment]
Fixed in 62ec3ac
